version: 2

project_name: tflint-ruleset-terraform-style

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    binary: tflint-ruleset-terraform_style
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - name_template: "tflint-ruleset-terraform_style_{{ .Os }}_{{ .Arch }}"
    formats: zip # Required by tflint
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

signs:
  - artifacts: checksum
    args: ["--batch", "-u", "{{ .Env.GPG_FINGERPRINT }}", "--output", "${signature}", "--detach-sign", "${artifact}"]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: Heldroe
    name: tflint-ruleset
